### ISSUE TITLE
test

### ISSUE THREAD

**Issue by GlukKazan** [GlukKazan/ZoG#1]
test

**Comment by gschmidt958** [comment]
Obviously, the test worked.
--------------------------------------------
On Tue, 5/3/16, GlukKazan <notifications@github.com> wrote:

 Subject: [GlukKazan/ZoG] test (#1)
 To: "GlukKazan/ZoG" <ZoG@noreply.github.com>
 Date: Tuesday, May 3, 2016, 3:39 AM
 
 test
 
 —
 You are receiving this because you are subscribed to this
 thread.
 Reply to this email directly or view it on
 GitHub

**Comment by GlukKazan** [comment]
Thanks, Greg :)
